name: 'Readme Action Template'
author: ganariya
description: 'This is the template of the readme update action.'

inputs:
  GH_TOKEN:
    description: 'GitHub access token with Repo scope'
    required: true
    default: ${{ github.token }}
  USERNAME:
    description: 'Your Account'
    required: true
  ATCODER_ACCOUNT:
    description: 'Your AtCoder Account'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'activity'
  color: 'orange'